### ISSUE TITLE
Access to Ref. Panels (Error 403)

### ISSUE THREAD

**Issue by vogulcan** [BlanchetteLab/RefHiC#1]
Hi folks;

Thank you for your contribution on 3D genome research, with this great tool, which i really would like to try with my data. However, i can not access to the reference panel hosted at http://repo.cs.mcgill.ca/PUB/blanchem/RefHiC/referencePanel.zip - hardcoded in config.ini -, in which it refuses my authorization to download it with wget. (Error 403)

Also, `refhic config init` returns with `KeyError: 'content-length'` in which, i believe its due to above reason.

Am i missing something? I'd be glad if you could direct me on the solution.

Thanks in advance;

**Comment by zhyanlin** [comment]
Hello,

Thanks for your interest. 
Our server seems offline. We are trying to get it back. Meanwhile, you can download our hg38 reference panel from zenodo: https://zenodo.org/record/6636796/files/referencePanel.zip .

You can update the URL in config.ini, or download it and deploy it by loading the reference panel from your local disk.

**Comment by vogulcan** [comment]
Thanks a lot. I managed to run predictions.
